// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);
