/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-18
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {
  var bar, foo, hoge, obj;

  hoge = "hoge";

  foo = 1;

  bar = false;

  console.log("ooge");

  obj = {
    title: "title",
    win: "win"
  };

}).call(this);
